<a href="https://colab.research.google.com/github/vitorjensen/Data-Science-para-Marketing/blob/main/Aula_01_Conhecendo_os_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
nome_influenciador = "Vitor"
print(nome_influenciador)

Vitor

In [ ]:
import pandas as pd

In [ ]:
campanha = pd.read_csv("/content/campanha.csv")

In [ ]:
campanha

,Id_campanha,impressoes,cliques,canal,custo,receita,estado,pais
0,1,152431,9462,Email,13258,32309,MG,Brasil
1,1,39688,3218,PPC,16391,16568,BA,Brasil
2,1,104506,4756,Google Ads,6189,19029,AL,Brasil
3,1,80768,3566,Google Ads,5215,0,PI,Brasil
4,1,54932,3645,Google Ads,16767,8825,RJ,Brasil
...,...,...,...,...,...,...,...,...
49995,2000,121275,7389,Social Media,25272,28441,MG,Brasil
49996,2000,121545,4203,Google Ads,9331,19679,MA,Brasil
49997,2000,132106,10254,Google Ads,13264,2111,RS,Brasil
49998,2000,131810,7159,PPC,12602,5602,DF,Brasil
49999,2000,162014,8155,Meta Ads,8908,4082,RJ,Brasil

In [ ]:
campanha.head()

   Id_campanha  impressoes  cliques       canal  custo  receita estado    pais
0            1      152431     9462       Email  13258    32309     MG  Brasil
1            1       39688     3218         PPC  16391    16568     BA  Brasil
2            1      104506     4756  Google Ads   6189    19029     AL  Brasil
3            1       80768     3566  Google Ads   5215        0     PI  Brasil
4            1       54932     3645  Google Ads  16767     8825     RJ  Brasil

In [ ]:
campanha['canal']

0               Email
1                 PPC
2          Google Ads
3          Google Ads
4          Google Ads
             ...
49995    Social Media
49996      Google Ads
49997      Google Ads
49998             PPC
49999        Meta Ads
Name: canal, Length: 50000, dtype: object

In [ ]:
campanha['canal'].unique()

array(['Email', 'PPC', 'Google Ads', 'Meta Ads', 'Social Media'],
      dtype=object)

In [ ]:
campanha['canal'].value_counts()

canal
Google Ads      25146
Meta Ads        15009
Social Media     4874
PPC              2526
Email            2445
Name: count, dtype: int64

Calculando a Métrica CTR

In [ ]:
campanha['ctr']=(campanha['cliques']/campanha['impressoes'])*100
campanha.head()

,Id_campanha,impressoes,cliques,canal,custo,receita,estado,pais,ctr
0,1,152431,9462,Email,13258,32309,MG,Brasil,6.207399
1,1,39688,3218,PPC,16391,16568,BA,Brasil,8.108244
2,1,104506,4756,Google Ads,6189,19029,AL,Brasil,4.550935
3,1,80768,3566,Google Ads,5215,0,PI,Brasil,4.415115
4,1,54932,3645,Google Ads,16767,8825,RJ,Brasil,6.635477